### PR TITLE
[ADDED] Automation Feature Functionality

### PR DESCRIPTION
**Pull request by LuluW8071**
- Create and Delete Directory
- Weather Function
- Youtube and Google Search

### CODE REVIEW

**Comment by LuluW8071** [comment]
@SabalM @404saugat404 Can you check the device control feature 
## Fix the timer delay and check if works on linux as well 

### - Added `Device OS Check` and execute system control commands
### - [TODO] Fix the `delay` 

However in windows i have checked only `sleep mode`

**Comment by SabalM** [comment]
>@LuluW8071  
>## tested the device control (sleep mode in windows)
>It returns response but the device does not go to sleep
>
>image
>
>Do I need to change or add anything before doing this?

**Comment by LuluW8071** [comment]
image
Insert the print msg to check logic

**Comment by LuluW8071** [comment]
Did you run `train.py` again?? You need to run again for new model due to changes in `intents.json`

**Pull request merged**
